export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const LOAD_MODES = 'LOAD_MODES';
export const LOAD_VERSIONS = 'LOAD_VERSIONS';
export const LOAD_SITEVERSIONS = 'LOAD_SITEVERSIONS';
export const CREATE_SITEVERSIONS = 'CREATE_SITEVERSIONS';
export const UPDATE_SITEVERSIONS = 'UPDATE_SITEVERSIONS';
export const DELETE_SITEVERSIONS = 'DELETE_SITEVERSIONS';
